### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by bencoman** [RMODINRIA/RoelTyper#1]
There is no license indicated in the repo. Presumably this was copied from...  http://www.squeaksource.com/RoelTyper.html

which defaults to the BSD license.  But it may be useful to see if [past contributors](http://www.squeaksource.com/RoelTyper/) would approve it being MIT.

**Comment by MarcusDenker** [comment]
Fixed by merging https://github.com/RMODINRIA/RoelTyper/pull/3
